---
name: PR Opened - Lint and Test Terraform Changes
run-name: Terraform Change Detected In PR ${{ github.event.number }} on ${{ github.head_ref }} - Lint and Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  terraform-validation:
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/terraform-lint-and-security-scan.yaml@main
    with:
      runs-on: ubuntu-latest
      infra-directory: ./