---
name: Push Main - Create Semantic Release
run-name: New Commit Detected on Main - Create Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    uses: Knighten-Homelab/gha-reusable-workflows/.github/workflows/semantic-release-to-gh.yaml@main
    with:
      runs-on: ubuntu-latest